In [23]:
import numpy as np

In [24]:
arr = np.random.random(size = (10,10))

In [25]:
arr

array([[0.7614327 , 0.70993794, 0.42316714, 0.02943104, 0.94698204,
        0.83272291, 0.51201716, 0.50909543, 0.27052619, 0.40531511],
       [0.45473212, 0.04230548, 0.06409389, 0.06939162, 0.59916832,
        0.26750261, 0.57332332, 0.51919789, 0.78977598, 0.02146953],
       [0.05031897, 0.75765613, 0.26144777, 0.04737033, 0.82322269,
        0.79277432, 0.43211528, 0.98069757, 0.10316815, 0.55967118],
       [0.79660084, 0.21000396, 0.79088585, 0.42372729, 0.3187753 ,
        0.36376908, 0.84738113, 0.06858305, 0.50638324, 0.10003661],
       [0.33682097, 0.81465929, 0.02089646, 0.21272752, 0.7049123 ,
        0.31333328, 0.27449113, 0.78140102, 0.67164521, 0.63663156],
       [0.05875269, 0.59580864, 0.07283352, 0.65680969, 0.35993484,
        0.36313448, 0.07548943, 0.34737179, 0.02817405, 0.32785917],
       [0.34079917, 0.56337682, 0.63889748, 0.0293378 , 0.30123208,
        0.23343097, 0.0378382 , 0.67791756, 0.59589771, 0.85562897],
       [0.38057337, 0.15957073, 0.7794037

In [29]:
# Method 1

arr[arr > 0.5] = 1
arr[arr < 0.5] = 0

In [30]:
arr

array([[1., 1., 0., 0., 1., 1., 1., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0., 1., 1., 1., 0.],
       [0., 1., 0., 0., 1., 1., 0., 1., 0., 1.],
       [1., 0., 1., 0., 0., 0., 1., 0., 1., 0.],
       [0., 1., 0., 0., 1., 0., 0., 1., 1., 1.],
       [0., 1., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 1., 0., 0., 0., 0., 1., 1., 1.],
       [0., 0., 1., 0., 1., 0., 0., 1., 1., 1.],
       [0., 0., 1., 0., 0., 1., 0., 1., 0., 1.],
       [0., 0., 1., 1., 0., 1., 1., 1., 0., 1.]])

In [28]:
# Method 2
res = np.where(arr > 0.5, 1, 0)
res

array([[1, 1, 0, 0, 1, 1, 1, 1, 0, 0],
       [0, 0, 0, 0, 1, 0, 1, 1, 1, 0],
       [0, 1, 0, 0, 1, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 0, 0, 1, 0, 1, 0],
       [0, 1, 0, 0, 1, 0, 0, 1, 1, 1],
       [0, 1, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 1, 1, 0, 0, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 1, 0, 0, 1, 1, 1],
       [0, 0, 1, 0, 0, 1, 0, 1, 0, 1],
       [0, 0, 1, 1, 0, 1, 1, 1, 0, 1]])