In [1]:
import numpy as np

In [7]:
arr = np.random.randint(1, 101, size = (5,5))

In [12]:
print(arr)

[[43 68 81 13 83]
 [21 72 15 90 60]
 [16 68 99 16 55]
 [34 86 79 98 96]
 [56 35 41 56 66]]


In [13]:
max_val = np.max(arr)

In [14]:
min_val = np.min(arr)

In [15]:
print("Max Value:", max_val)

Max Value: 99


In [16]:
print("Min Value:", min_val)

Min Value: 13
