In [1]:
import numpy as np

In [18]:
arr = np.random.random(size = (3,3))

In [19]:
arr

array([[0.25626381, 0.52257894, 0.62885324],
       [0.80239717, 0.60240963, 0.65451221],
       [0.03973806, 0.50662717, 0.86916184]])

In [20]:
np.transpose(arr)

array([[0.25626381, 0.80239717, 0.03973806],
       [0.52257894, 0.60240963, 0.50662717],
       [0.62885324, 0.65451221, 0.86916184]])

In [22]:
arr.T

array([[0.25626381, 0.80239717, 0.03973806],
       [0.52257894, 0.60240963, 0.50662717],
       [0.62885324, 0.65451221, 0.86916184]])