In [2]:
import numpy as np

In [6]:
arr = np.random.random((3,3))

In [14]:
print(arr)

[[0.57240292 0.79154436 0.13311366]
 [0.79501917 0.69999108 0.99731144]
 [0.34478633 0.41920653 0.99855819]]


In [16]:
print(arr[1,2])

0.9973114371605535
