In [1]:
import numpy as np

In [3]:
arr = np.array([[1,2,3],
                [4,5,6],
                [7,8,9]])

In [4]:
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [7]:
sum_of_rows = arr.sum(axis = 1)

In [8]:
print(sum_of_rows)

[ 6 15 24]


In [11]:
sum_of_cols = arr.sum(axis = 0)

In [12]:
print(sum_of_cols)

[12 15 18]
